pipeline {
    agent { label 'agent1' }
    stages {
        stage('Build') { // First stage: Build
            steps {
                echo 'Building Container...'
                // Commands to build the project
                //sh 'docker-compose up -d' 
                sh 'touch smita.txt'
            }
        }
        
        }
    }
